---
# tasks file for Debian-elk
- name: Installing FTP server for Debian
  apt:
   name: vsftpd
   state: latest
   update_cache: yes

- name: Start FTP service
  service:
   name: vsftpd
   state: started
   enabled: yes

- name: Create FTP user
  user:
   name: '{{ user }}'
   password: '{{ ftp_pass }}

- name: Denying user access for SSH
  lineinfile:
   path: /etc/ssh/sshd_config
   line: "DenyUsers '{{ user }}'"
  register: denied_successfully

- name: Restarting SSHD service
  service:
   name: sshd
   state: restarted
  when: denied_successfully.changed

- name: Copying configuration file
  copy:
   src: /etc/vsftpd/vsftpd.conf
   dest: /etc/vsftpd/vsftpd.conf.default
   remote_stc: True

- name: Limiting FTP users
  replace:
   path: /etc/vsftpd/vsftpd.conf
   regexp: '#chroot_local_user=YES'
   replace: 'chroot_local_user=YES'

- name: Configuring FTP file
  lineinfile:
   path: /etc/vsftpd/vsftpd.conf
   line: '{{ ftp_config }}'

- name: Restart vsftpd
  service:
   name: vsftpd
   state: restarted
