---
# Install python3 and pip3
- name: Installing Python3 and Pip3 latest
  apt:
    name:
      - python3
      - python3-pip
    state: latest
    update_cache: yes

- name: Use pip3 as default pip
  shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

- name: Use python3 as default python
  shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 10

